version: '3.6'
services:
  db:
    image: postgres:16.1-bullseye
    environment:
      TZ: Europe/Warsaw
      POSTGRES_DB: pastebin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - /home/volumes/db:/var/lib/postgresql/data
  redis:
    image: redis
    environment:
      TZ: Europe/Warsaw
    ports:
      - '6379:6379'