# Generated by Django 5.0.3 on 2024-03-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_notepasswordmodel_iterations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='text',
            field=models.BinaryField(),
        ),
    ]
