# Generated by Django 5.0.3 on 2024-03-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_notemodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
