# Generated by Django 5.0.3 on 2024-03-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_notemodel_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='expiration_type',
            field=models.CharField(choices=[('NEVER', 'Never'), ('BURN_AFTER_READ', 'Burn After Read'), ('FIVE_MINUTES', 'Five Minutes'), ('TEN_MINUTES', 'Ten Minutes'), ('ONE_HOUR', 'One Hour'), ('ONE_DAY', 'One Day'), ('ONE_WEEK', 'One Week'), ('TWO_WEEKS', 'Two Weeks'), ('ONE_MONTH', 'One Month'), ('TWO_MONTHS', 'Two Months'), ('THREE_MONTHS', 'Three Months'), ('SIX_MONTHS', 'Six Months'), ('ONE_YEAR', 'One Year')], default='NEVER', max_length=50),
        ),
    ]
